/* src/stconfig.h.  Generated by configure.  */
/* src/stconfig.h.in.  Generated from configure.ac by autoheader.  */

/* Define if you are using an external GSM library */
/* #undef EXTERNAL_GSM */

/* Define to 1 if you have ALSA. */
/* #undef HAVE_ALSA */

/* Define to 1 if you have the <alsa/asoundlib.h> header file. */
/* #undef HAVE_ALSA_ASOUNDLIB_H */

/* Define to 1 if you have the <byteswap.h> header file. */
/* #undef HAVE_BYTESWAP_H */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if fseeko (and presumably ftello) exists and is declared. */
#define HAVE_FSEEKO 1

/* Define to 1 if you have the `getopt_long' function. */
#define HAVE_GETOPT_LONG 1

/* Define to 1 if you have the <gsm/gsm.h> header file. */
/* #undef HAVE_GSM_GSM_H */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `asound' library (-lasound). */
/* #undef HAVE_LIBASOUND */

/* Define to 1 if you have the `FLAC' library (-lFLAC). */
/* #undef HAVE_LIBFLAC */

/* Define to 1 if you have the `m' library (-lm). */
/* #undef HAVE_LIBM */

/* Define to 1 if you have the `mad' library (-lmad). */
/* #undef HAVE_LIBMAD */

/* Define to 1 if you have the `mp3lame' library (-lmp3lame). */
/* #undef HAVE_LIBMP3LAME */

/* Define to 1 if you have the `ogg' library (-logg). */
/* #undef HAVE_LIBOGG */

/* Define to 1 if you have the `vorbisenc' library (-lvorbisenc). */
/* #undef HAVE_LIBVORBISENC */

/* Define to 1 if you have the `vorbisfile' library (-lvorbisfile). */
/* #undef HAVE_LIBVORBISFILE */

/* Define to 1 if you have the <machine/soundcard.h> header file. */
/* #undef HAVE_MACHINE_SOUNDCARD_H */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have OSS. */
/* #undef HAVE_OSS */

/* Define if you have <samplerate.h> */
/* #undef HAVE_SAMPLERATE_H */

/* Define if you have libsndfile >= 1.0.12 */
/* #undef HAVE_SNDFILE_1_0_12 */

/* Define if you have <sndfile.h> */
/* #undef HAVE_SNDFILE_H */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have Sun /dev/audio. */
/* #undef HAVE_SUN_AUDIO */

/* Define to 1 if you have the <sun/audioio.h> header file. */
/* #undef HAVE_SUN_AUDIOIO_H */

/* Define to 1 if you have the <sys/audioio.h> header file. */
/* #undef HAVE_SYS_AUDIOIO_H */

/* Define to 1 if you have the <sys/soundcard.h> header file. */
/* #undef HAVE_SYS_SOUNDCARD_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "sox"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "sox-devel@lists.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "SoX"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "SoX 13.0.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "sox"

/* Define to the version of this package. */
#define PACKAGE_VERSION "13.0.0"

/* The size of a `char', as computed by sizeof. */
/* #undef SIZEOF_CHAR */

/* The size of a `int', as computed by sizeof. */
/* #undef SIZEOF_INT */

/* The size of a `long', as computed by sizeof. */
/* #undef SIZEOF_LONG */

/* The size of a `short', as computed by sizeof. */
/* #undef SIZEOF_SHORT */

/* The size of a `void*', as computed by sizeof. */
/* #undef SIZEOF_VOIDP */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "13.0.0"

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Number of bits in a file offset, on hosts where this is settable. */
/* #undef _FILE_OFFSET_BITS */

/* Define to 1 to make fseeko visible on some hosts (e.g. glibc 2.2). */
/* #undef _LARGEFILE_SOURCE */

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif
